### ISSUE TITLE
Move the repository under the AmarilloTechMeetup Organization?

### ISSUE THREAD

**Issue by ScriptGadget** [jamesleebaker/events-frontend#2]
@jamesleebaker I've created an Amarillo Tech Meetup organization. Should we move this repository there? Or would you prefer I clone it?

**Comment by ilcrawford** [comment]
I'm good with moving it.  I will need some help on how to change my pull requests to go to the new repository.

**Comment by ScriptGadget** [comment]
I went ahead and forked it. I've merged your latest pull request here and then pulled the changes to the fork under AmarilloTechMeetup. The cleanest way to move forward is to blow away your local clone and pull a new clone from git@github.com:AmarilloTechMeetup/events-frontend.git
